<?php
// $Id$
/**
 * @file
 * Adds a slideshare feed processor to the Feeds module.
 */

/**
 * Implementation of hook_feeds_plugins().
 */
function feeds_slideshare_feeds_plugins() {
  $info = array();
  $info['FeedsSlideshareParser'] = array(
    'name' => 'Slideshare parser',
    'description' => 'Parse Slideshare feeds.',
    'help' => 'Use PHP SimpleXML parser to parse Slideshare feeds.',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'FeedsSlideshareParser',
      'file' => 'FeedsSlideshareParser.inc',
      'path' => drupal_get_path('module', 'feeds_slideshare'),
    ),
  );
//  if (feeds_library_exists('simplepie.inc', 'simplepie')) {
//    $info['FeedsSlideshareSimplePieParser'] = array(
//      'name' => 'slideshare parser',
//      'description' => 'Parse slideshare feeds using SimplePie library.',
//      'help' => 'Use <a href="http://simplepie.org">SimplePie</a> to parse slideshare feeds.',
//      'handler' => array(
//        'parent' => 'FeedsSimplePieParser',
//        'class' => 'FeedsslideshareParser',
//        'file' => 'FeedsSlideshareSimplePieParser.inc',
//        'path' => drupal_get_path('module', 'feeds_slideshare'),
//      ),
//    );
//  }
  return $info;
}
